# Generated by Django 4.2.10 on 2024-05-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_ticket_pdf_filename"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketsalesreport",
            name="total_sales_class",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="ticketsalesreport",
            name="total_sales_route",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
