# Generated by Django 4.2.10 on 2024-05-19 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_ticketsalesreport_total_sales_class_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticketsalesreport",
            name="total_sales_class",
        ),
        migrations.RemoveField(
            model_name="ticketsalesreport",
            name="total_sales_route",
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[("Cash", "Cash"), ("Card", "Card")],
                default="Cash",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="ticket",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment",
                to="main.ticket",
            ),
        ),
    ]
