# Generated by Django 4.2.10 on 2024-05-20 19:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_remove_ticketsalesreport_total_sales_class_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="administrator",
            name="user",
        ),
        migrations.RemoveField(
            model_name="bookinghistory",
            name="ticket",
        ),
        migrations.RemoveField(
            model_name="bookinghistory",
            name="user",
        ),
        migrations.DeleteModel(
            name="ValidationGate",
        ),
        migrations.DeleteModel(
            name="Administrator",
        ),
        migrations.DeleteModel(
            name="BookingHistory",
        ),
    ]
