# Generated by Django 4.2.10 on 2024-06-04 07:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_seat_remove_ticket_seat_number_alter_ticket_route_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="seat",
        ),
        migrations.AddField(
            model_name="ticket",
            name="is_seat_booked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="ticket",
            name="seat_class",
            field=models.CharField(
                choices=[
                    ("Economy", "Economy"),
                    ("Standard", "Standard"),
                    ("Business", "Business"),
                ],
                default="A1",
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ticket",
            name="seat_number",
            field=models.CharField(
                choices=[
                    ("B1", "B1"),
                    ("B2", "B2"),
                    ("B3", "B3"),
                    ("B4", "B4"),
                    ("B5", "B5"),
                    ("B6", "B6"),
                    ("S1", "S1"),
                    ("S2", "S2"),
                    ("S3", "S3"),
                    ("S4", "S4"),
                    ("S5", "S5"),
                    ("S6", "S6"),
                    ("E1", "E1"),
                    ("E2", "E2"),
                    ("E3", "E3"),
                    ("E4", "E4"),
                    ("E5", "E5"),
                    ("E6", "E6"),
                ],
                default=1,
                max_length=5,
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Seat",
        ),
    ]
