# Generated by Django 4.2.10 on 2024-06-05 03:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0009_remove_ticket_seat_ticket_is_seat_booked_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("passenger", "Passenger"),
                    ("admin", "Admin"),
                    ("financial_manager", "Financial Manager"),
                ],
                default="passenger",
                max_length=20,
            ),
        ),
    ]
