# Generated by Django 4.2.10 on 2024-06-05 03:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0010_user_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="role",
        ),
    ]
